# Generated by Django 3.0.3 on 2020-05-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200503_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telephone_numb',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
