# Generated by Django 3.0.3 on 2020-06-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200605_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firstName',
            field=models.CharField(db_index=True, default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastName',
            field=models.CharField(db_index=True, default='none', max_length=255),
        ),
    ]
