# Generated by Django 3.0.3 on 2020-06-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200606_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lastName',
        ),
    ]
