# Generated by Django 3.0.3 on 2020-05-31 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200531_0859'),
        ('news', '0002_auto_20200525_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='goods.Product'),
        ),
    ]
