# Generated by Django 3.0.3 on 2020-05-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200515_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telephone_numb',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
