# Generated by Django 3.0.3 on 2020-05-25 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='goods.Product')),
            ],
        ),
    ]
