# Generated by Django 3.0.3 on 2020-05-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='order_date',
            new_name='order_status_date',
        ),
        migrations.AlterUniqueTogether(
            name='orderstatus',
            unique_together={('order', 'order_status_date', 'ord_status')},
        ),
    ]
