# Generated by Django 3.0.3 on 2020-05-29 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200529_1021'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderstatus',
            unique_together={('order', 'order_status_date', 'ord_status')},
        ),
    ]
